apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubernetes.io/change-cause: kubectl set image deployment hello-world-rest-api
      hello-world-rest-api=willyborja95/hello-world-rest-api:0.0.4-SNAPSHOT --record=true
  creationTimestamp: "2021-01-05T22:28:21Z"
  generation: 5
  labels:
    app: hello-world-rest-api
  name: hello-world-rest-api
  namespace: default
  resourceVersion: "25109"
  selfLink: /apis/apps/v1/namespaces/default/deployments/hello-world-rest-api
  uid: e25e5427-dfb5-495b-a798-cc0600c84a5e
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hello-world-rest-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-world-rest-api
    spec:
      containers:
      - image: willyborja95/hello-world-rest-api:0.0.4-SNAPSHOT
        imagePullPolicy: Always
        name: hello-world-rest-api
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-01-05T22:30:42Z"
    lastUpdateTime: "2021-01-05T22:30:42Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-01-05T22:28:21Z"
    lastUpdateTime: "2021-01-05T23:35:57Z"
    message: ReplicaSet "hello-world-rest-api-85b5855f5c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
